import ccxt
import datetime
from typing import Dict, Any

class OrderManager:
    """Handles order placement, stop‑loss and target (take‑profit) on a given exchange.
    
    Currently supports market orders and OCO (one‑cancel‑the‑other) if the exchange provides it.
    """
    def __init__(self, exchange_name: str = "binance", api_key: str = "YOUR_API_KEY", secret: str = "YOUR_SECRET"):
        self.exchange = getattr(ccxt, exchange_name)({
            "apiKey": api_key,
            "secret": secret,
            "enableRateLimit": True,
        })
        # Attempt to load markets; gracefully handle auth errors or missing keys
        try:
            self.exchange.load_markets()
        except Exception as e:
            # If authentication fails (common in dev with placeholder keys), continue without markets
            print(f"[OrderManager] Warning: could not load markets – {e}")
            self.exchange = None

        # Simple capital tracking (placeholder)
        self.account_balance = self._fetch_balance()

    def _fetch_balance(self) -> float:
        # Fetch total USDT (or base currency) balance – fallback to 0 if unavailable
        try:
            bal = self.exchange.fetch_balance()
            # Try common keys
            for key in ("USDT", "USD", "free"):
                if key in bal and isinstance(bal[key], dict) and "total" in bal[key]:
                    return float(bal[key]["total"])
            return float(bal.get("total", 0))
        except Exception:
            return 0.0

    def place_order(
        self,
        symbol: str,
        side: str,
        amount: float,
        price: float = None,
        stop_loss: float = None,
        take_profit: float = None,
    ) -> Dict[str, Any]:
        """Place a market order with optional stop‑loss and take‑profit.
        
        Parameters
        ----------
        symbol: Trading pair, e.g. "BTC/USDT"
        side: "buy" or "sell"
        amount: Quantity in base asset
        price: Ignored for market orders (kept for API compatibility)
        stop_loss: Price level for stop‑loss (absolute price)
        take_profit: Price level for take‑profit (absolute price)
        """
        # Market order (safe version)
        if self.exchange is None:
            print("[OrderManager] No exchange configured – returning mock order.")
            order = {"id": "mock-order", "info": "dry-run", "symbol": symbol, "type": "market", "side": side, "amount": amount}
        else:
            order = self.exchange.create_market_order(symbol, side, amount)
        order_id = order.get("id")
        # If stop‑loss / TP provided and exchange supports OCO, create OCO order
        if (stop_loss or take_profit) and self.exchange is not None:
            try:
                # Many exchanges use create_order with type='stop'
                # Here we implement a simple fallback: place separate stop and limit orders.
                if stop_loss:
                    self.exchange.create_order(
                        symbol,
                        type="stop",
                        side="sell" if side == "buy" else "buy",
                        amount=amount,
                        price=stop_loss,
                    )
                if take_profit:
                    self.exchange.create_order(
                        symbol,
                        type="limit",
                        side="sell" if side == "buy" else "buy",
                        amount=amount,
                        price=take_profit,
                    )
            except Exception as e:
                # Log but continue – in production replace with proper logger
                print(f"Failed to place SL/TP orders: {e}")
        return {"market_order": order, "status": "submitted"}

    def execute(self, order: dict) -> dict:
        """Execute an order dict generated by StrategyEngine.

        Parameters
        ----------
        order: dict
            Expected keys: symbol, side, size, price, stop_loss, take_profit.
            If ``side`` is ``None`` no trade is performed.
        """
        side = order.get("side")
        if not side:
            return {"status": "no_action", "reason": "Strategy produced no signal"}
        return self.place_order(
            symbol=order.get("symbol"),
            side=side,
            amount=order.get("size"),
            price=order.get("price"),
            stop_loss=order.get("stop_loss"),
            take_profit=order.get("take_profit"),
        )

    def __repr__(self) -> str:
        return f"OrderManager(exchange={self.exchange.id}, balance={self.account_balance})"
